name: Build PyQt5 App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get install -y python3-dev libxcb-xinerama0

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name MyApp main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: dist/

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name MyApp main.py

      - name: Create .dmg (macOS)
        run: |
          brew install create-dmg
          mkdir -p dmg_build
          cp -r dist/MyApp.app dmg_build/
          create-dmg \
            --volname "MyApp Installer" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "MyApp.app" 200 190 \
            --hide-extension "MyApp.app" \
            --app-drop-link 600 185 \
            "MyApp.dmg" \
            "dmg_build/"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: |
            dist/MyApp.app
            MyApp.dmg